### PR TITLE
Use ably fork README for NPM publish

### PR DESCRIPTION
**Pull request by owenpearson**
Currently the upstream laravel/echo README appears on npmjs.com/packages/@ably/laravel-echo. This PR adds pre/post publish scripts to temporarily move `.github/README.md` to the root while publishing.

### CODE REVIEW

**Review by stmoreau — APPROVED** [review]

**Comment by sacOO7** [comment]
Will this script work on windows machines too ?

**Comment by owenpearson** [comment]
@sacOO7 depends if you use a POSIX shell (git bash, WSL, CYGWIN, etc) 😄

**Comment by owenpearson** [comment]
@sacOO7 I've updated it to use a cross-platform `mv` command

**Review by sacOO7 — APPROVED** [review]
LGTM

**Review by sacOO7 — CHANGES_REQUESTED** [review]
Ohh sorry we need to use the command twice right

**Comment by owenpearson** [comment]
@sacOO7 oops, good spot. fixed now

**Review by sacOO7 — APPROVED** [review]
LGTM

**Review by qsdstefan — APPROVED** [review]
LGTM

**Pull request merged**
